"""empty message

Revision ID: 322bd2efc44f
Revises: 89ab4f84ffe2
Create Date: 2021-12-24 10:58:52.742534

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '322bd2efc44f'
down_revision = '89ab4f84ffe2'
branch_labels = None
depends_on = None


def upgrade():
    
    schema='auth'

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema=schema
    )

    op.drop_column('users', 'is_staff', schema=schema)
    op.drop_column('users', 'is_active', schema=schema)
    op.drop_column('users', 'is_superuser', schema=schema)

    op.create_table('user_role',
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('role_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.UniqueConstraint('user_id', 'role_id', name='uniq_user_role'),
    schema=schema
    )
    # ### end Alembic commands ###


def downgrade():

    schema='auth'

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role', schema='auth')
    
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=True), schema=schema)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True), schema=schema)
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True), schema=schema)

    op.drop_table('roles', schema='auth')
    # ### end Alembic commands ###
